### ISSUE TITLE
Got doesn't report errors

### ISSUE THREAD

**Issue by nateGeorge** [vdemedes/google-images#12]
When there is an error (i.e., I was over my quota for searches) it is not reported to the console.

The 'got' call should look more like this:

```
got('todomvc.com')
    .then(response => {
        console.log(response.body);
        //=> '<!doctype html> ...' 
    })
    .catch(error => {
        console.log(error.response.body);
        //=> 'Internal server error ...' 
    });
```

https://www.npmjs.com/package/got

**Comment by vdemedes** [comment]
See https://github.com/vdemedes/google-images/pull/13#issuecomment-236418543.
