### ISSUE TITLE
size parameter needs to be capitalized

### ISSUE THREAD

**Issue by nateGeorge** [vdemedes/google-images#14]
In the example and test, the size parameter (i.e. 'large') should be capitalized ('Large').

**Comment by nateGeorge** [comment]
After checking the docs, this doesn't need to be capitalized.
https://developers.google.com/custom-search/json-api/v1/reference/cse/list

**Comment by r3verser** [comment]
How to filter by date for example? And why in google cse/list parameter name is "imgSize", but in this script it's just "size"?

**Comment by nateGeorge** [comment]
That's just how it is in the code: 		
```
if (options.size) {
	result.imgSize = options.size;
}
```
Dunno how to filter by date, sorry.  Probably those google docs can help you.
